@startuml
User->Flowable:just(item)
Flowable->FlowableJust:new FlowableJust(item)
Flowable->RxJavaPlugins:onAssembly
RxJavaPlugins->onFlowableAssembly:aply(FlowableJust)


'
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml